-- MySQL Script generated by MySQL Workbench
-- Wed 30 Oct 2024 10:09:58 AM WIB
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET UTF8;
SHOW WARNINGS;

USE `mydb` ;
SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Stock Update`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Stock Update` (
  `stock-UpdateID` INT NOT NULL AUTO_INCREMENT,
  `bookID` INT NOT NULL,
  `stockDate` DATETIME NULL,
  `quantityStock` INT NULL,
  `reasonStock` TEXT NULL,
  PRIMARY KEY (`stock-UpdateID`),
  INDEX `fk_Stock Update_1_idx` (`bookID` ASC) VISIBLE,
  CONSTRAINT `fk_Stock Update_1`
    FOREIGN KEY (`bookID`)
    REFERENCES `mydb`.`Books` (`bookID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Employe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Employe` (
  `employeID` INT NOT NULL AUTO_INCREMENT,
  `name-employee` INT NULL,
  `contact-employee` VARCHAR(45) NULL UNIQUE,
  `bookID` INT NULL,
  `email-employee` VARCHAR(45) NULL UNIQUE,
  `role_employee` ENUM('admin', 'logistik', 'administrasi') NULL,
  `stock-UpdateID` INT NULL,
  PRIMARY KEY (`employeID`),
  INDEX `fk_Employe_1_idx` (`bookID` ASC) VISIBLE,
  UNIQUE INDEX `email-employee_UNIQUE` (`email-employee` ASC) VISIBLE,
  INDEX `fk_Employe_2_idx` (`stock-UpdateID` ASC) VISIBLE,
  CONSTRAINT `fk_Employe_1`
    FOREIGN KEY (`bookID`)
    REFERENCES `mydb`.`Books` (`bookID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Employe_2`
    FOREIGN KEY (`stock-UpdateID`)
    REFERENCES `mydb`.`Stock Update` (`stock-UpdateID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`Order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Order` (
  `orderID` INT NOT NULL AUTO_INCREMENT,
  `OrderDate` DATETIME NULL,
  `TotalOrderAmount` DECIMAL NULL,
  `customerID` INT NULL,
  `transaksiID` INT NULL,
  PRIMARY KEY (`orderID`),
  INDEX `fk_Order_Customer1_idx` (`customerID` ASC) VISIBLE,
  INDEX `fk_Order_Sales Transaksi1_idx` (`transaksiID` ASC) VISIBLE,
  CONSTRAINT `fk_Order_Customer1`
    FOREIGN KEY (`customerID`)
    REFERENCES `mydb`.`Customer` (`customerID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Order_Sales Transaksi1`
    FOREIGN KEY (`transaksiID`)
    REFERENCES `mydb`.`Sales Transaksi` (`transaksiID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`Sales Transaksi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Sales Transaksi` (
  `transaksiID` INT NOT NULL AUTO_INCREMENT,
  `transaksiDate` DATETIME NULL,
  `totalAmount` DECIMAL NULL,
  `payment-methode` ENUM('cash', 'transfer bank', 'virtual bank', 'e-wallet') NULL,
  `orderID` INT NULL,
  `employeID` INT NULL,
  PRIMARY KEY (`transaksiID`),
  INDEX `fk_Sales Transaksi_Employe1_idx` (`employeID` ASC) VISIBLE,
  INDEX `fk_Sales Transaksi_1_idx` (`orderID` ASC) VISIBLE,
  CONSTRAINT `fk_Sales Transaksi_Employe1`
    FOREIGN KEY (`employeID`)
    REFERENCES `mydb`.`Employe` (`employeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Sales Transaksi_1`
    FOREIGN KEY (`orderID`)
    REFERENCES `mydb`.`Order` (`orderID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`Books`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Books` (
  `bookID` INT NOT NULL AUTO_INCREMENT,
  `title-book` VARCHAR(45) NULL,
  `authors-book` VARCHAR(45) NULL,
  `genre-book` ENUM('horor', 'fantasy', 'history', 'technology', 'biology', 'animal', '...') NULL,
  `stock-book` INT NULL,
  `price` DECIMAL NULL,
  `isbn` VARCHAR(45) NULL,
  `publisher` VARCHAR(45) NULL,
  `sinopsis-book` LONGTEXT NULL,
  `transaksiID` INT NULL,
  `customerID` INT NULL,
  PRIMARY KEY (`bookID`),
  INDEX `fk_Books_1_idx` (`customerID` ASC) VISIBLE,
  INDEX `fk_Books_2_idx` (`transaksiID` ASC) VISIBLE,
  CONSTRAINT `fk_Books_1`
    FOREIGN KEY (`customerID`)
    REFERENCES `mydb`.`Customer` (`customerID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Books_2`
    FOREIGN KEY (`transaksiID`)
    REFERENCES `mydb`.`Sales Transaksi` (`transaksiID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`Rekomendasi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Rekomendasi` (
  `rekomendasiID` INT NOT NULL AUTO_INCREMENT,
  `bookID` INT NULL,
  `genre-book` VARCHAR(45) NULL,
  `title-book` VARCHAR(45) NULL,
  `authors-book` VARCHAR(45) NULL,
  PRIMARY KEY (`rekomendasiID`),
  INDEX `fk_Rekomendasi_1_idx` (`bookID` ASC) VISIBLE,
  CONSTRAINT `fk_Rekomendasi_1`
    FOREIGN KEY (`bookID`)
    REFERENCES `mydb`.`Books` (`bookID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`Customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Customer` (
  `customerID` INT NOT NULL AUTO_INCREMENT,
  `username-customer` INT NOT NULL, -- Adjusted to match foreign key requirement
  `contact-customer` VARCHAR(45) NULL,
  `email-customer` VARCHAR(45) NULL,
  `address-costumer` INT NULL,
  `rekomendasiID` INT NULL,
  PRIMARY KEY (`customerID`),
  UNIQUE INDEX `email-customer_UNIQUE` (`email-customer` ASC),
  CONSTRAINT `fk_Customer_1`
    FOREIGN KEY (`rekomendasiID`)
    REFERENCES `mydb`.`Rekomendasi` (`rekomendasiID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;
-- -----------------------------------------------------
-- Table `mydb`.`Shipment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Shipment` (
  `shipmentID` INT NOT NULL AUTO_INCREMENT,
  `shipment-date` DATETIME NULL,
  `delivery-method` ENUM('pick up', 'delivery') NULL,
  `shipment-addressID` INT NULL,
  `status-shipment` ENUM('shipped', 'pending', 'delivered', 'canceled') NULL, -- Updated ENUM values
  `trackingNumber-shipment` VARCHAR(45) NULL UNIQUE,
  `orderID` INT NULL,
  PRIMARY KEY (`shipmentID`),
  INDEX `fk_Shipment_Order1_idx` (`orderID` ASC),
  CONSTRAINT `fk_Shipment_Order1`
    FOREIGN KEY (`orderID`)
    REFERENCES `mydb`.`Order` (`orderID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;
-- -----------------------------------------------------
-- Table `mydb`.`Address-Costumer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Address-Costumer` (
  `address-costumer` INT NOT NULL AUTO_INCREMENT,
  `state-address` VARCHAR(45) NULL,
  `city-address` VARCHAR(45) NULL,
  `postal-code` VARCHAR(45) NULL,
  `country-address` ENUM('indonesia', 'japan', 'singapore', 'malaysia', 'china', 'philipine', 'australia', '...') NULL,
  `customerID` INT NULL,
  PRIMARY KEY (`address-costumer`),
  INDEX `fk_Address-Costumer_Customer2_idx` (`customerID` ASC) VISIBLE,
  CONSTRAINT `fk_Address-Costumer_Customer2`
    FOREIGN KEY (`customerID`)
    REFERENCES `mydb`.`Customer` (`customerID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`Name-Customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Name-Customer` (
  `username-customerID` INT NOT NULL AUTO_INCREMENT,  
  `first-name-customer` VARCHAR(45) NULL,
  `last-name-customer` VARCHAR(45) NULL,
  `customerID` INT NULL,
  PRIMARY KEY (`username-customerID`),
  CONSTRAINT `fk_Name-Customer_Customer2`
    FOREIGN KEY (`customerID`)
    REFERENCES `mydb`.`Customer` (`customerID`) -- Corrected the foreign key to `customerID`
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;
-- -----------------------------------------------------
-- Table `mydb`.`Name-Employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Name-Employee` (
  `name-employeeID` INT NOT NULL AUTO_INCREMENT,
  `first-name-employee` VARCHAR(45) NULL,
  `last-name-customer` VARCHAR(45) NULL,
  `username-employee` VARCHAR(45) NULL,
  `employeID` INT NULL,
  PRIMARY KEY (`name-employeeID`),
  INDEX `fk_Name-Employee_Employe1_idx` (`employeID` ASC) VISIBLE,
  CONSTRAINT `fk_Name-Employee_Employe1`
    FOREIGN KEY (`employeID`)
    REFERENCES `mydb`.`Employe` (`employeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`Shipment-Address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Shipment-Address` (
  `shipment-addressID` INT NOT NULL AUTO_INCREMENT,
  `shipment-address-city` VARCHAR(45) NULL,
  `shipment-address-country` VARCHAR(45) NULL,
  `shipment-address-state` VARCHAR(45) NULL,
  `shipment-address-postal-code` VARCHAR(45) NULL,
  `shipmentID` INT NULL,
  PRIMARY KEY (`shipment-addressID`),
  INDEX `fk_Shipment-Address_Shipment1_idx` (`shipmentID` ASC) VISIBLE,
  CONSTRAINT `fk_Shipment-Address_Shipment1`
    FOREIGN KEY (`shipmentID`)
    REFERENCES `mydb`.`Shipment` (`shipmentID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

INSERT INTO `Customer` (`username-customer`, `contact-customer`, `email-customer`, `address-costumer`, `rekomendasiID`)
VALUES 
(101, '33243456', 'cusmer1@example.com', NULL, NULL),
(102, '23456890', 'ustr1@example.com', NULL, NULL),
(103, '12347890', '2123stom1@example.com', NULL, NULL),
(104, '14567890', 'tm3211@example.com', NULL, NULL),
(105, '34214567', 'mer121@example.com', NULL, NULL),
(106, '43456890', '32strsfa1@example.com', NULL, NULL),
(107, '22347890', '1ctom1wqw@example.com', NULL, NULL),
(108, '44567890', '21ctm1sa@example.com', NULL, NULL),
(109, '38874567', 'eqwctomerdwag1@example.com', NULL, NULL),
(110, '23450090', 'vrscstr1dwa@example.com', NULL, NULL),
(111, '32145890', 'e3q2o231m1@example.com', NULL, NULL),
(112, '31267890', '31um144@example.com', NULL, NULL),
(113, '34123567', 'gtrustomer31241@example.com', NULL, NULL),
(114, '24532890', 'htjustr1fesxf@example.com', NULL, NULL),
(115, '13234790', 'njmutomrewg1@example.com', NULL, NULL),
(116, '14568990', 'klhcutm1grwer@example.com', NULL, NULL),
(117, '78734567', 'loicstomerqqe1@example.com', NULL, NULL),
(118, '79456890', 'ipustr1ee3q@example.com', NULL, NULL),
(119, '96347890', 'uyrstom879781@example.com', NULL, NULL),
(120, '87567890', 'tuiftcutm1htf@example.com', NULL, NULL),
(121, '30004567', 'fewecomefesdr1@example.com', NULL, NULL),
(122, '83456890', 'e3qwcustrads1@example.com', NULL, NULL),
(123, '72347890', 'ewqfctodasm1@example.com', NULL, NULL),
(124, '89567890', 'rtwcutfersm1@edawdxample.com', NULL, NULL),
(125, '34567000', 'fewjwcuomdwweer1@example.com', NULL, NULL);

-- Data Insertion for the `Name-Customer` table
INSERT INTO `Name-Customer` (`customerID`, `first-name-customer`, `last-name-customer`, `username-customerID`)
VALUES 
(1, 'John', 'C', 101),
(2, 'John', 'Smith', 102),
(3, 'Sarah', 'Davis', 103),
(4, 'Emily', 'Stomer', 104),
(5, 'Taylor', 'Custom', 105),
(6, 'Fist', 'Cuomer', 106),
(7, 'William', 'Ctomer', 107),
(8, 'Wlan', 'Tomer', 108),
(9, 'Fir', 'Tom', 109),
(10, 'Olive', 'Oil', 110),
(11, 'Wiliam', 'Taylor', 111),
(12, 'Liam', 'Black', 112),
(13, 'Tom', 'Custom', 113),
(14, 'Bean', 'Hill', 114),
(15, 'Thomas', 'Ctomer', 115),
(16, 'Lewis', 'Stomer', 116),
(17, 'Aca', 'Custom', 117),
(18, 'Ava', 'Cuomer', 118),
(19, 'Scot', 'Ctomer', 119),
(20, 'Ethan', 'stomer', 120),
(21, 'Mia', 'Custom', 121),
(22, 'Allen', 'Cuomerso', 122),
(23, 'Clark', 'Ctomer', 123),
(24, 'Young', 'Stomer', 124),
(25, 'Allan', 'Wake', 125);

-- Data Insertion for the `Shipment` table
INSERT INTO `Shipment` (`shipmentID`, `shipment-date`, `delivery-method`, `shipment-addressID`, `status-shipment`, `trackingNumber-shipment`, `orderID`)
VALUES 
(1, NOW(), 'delivery', 1, 'shipped', 'TRACK123', 1);


-- Insert data into Address-Costumer table
INSERT INTO `Address-Costumer` (`address-costumer`, `state-address`, `city-address`, `postal-code`, `country-address`, `customerID`)
VALUES 
(1, 'State A', 'City A', '12345', 'indonesia', 1);

-- Insert data into Rekomendasi table (no foreign key dependency)
INSERT INTO `Rekomendasi` (`rekomendasiID`, `bookID`, `genre-book`, `title-book`, `authors-book`)
VALUES 
(1, 1, 'fantasy', 'Book Title 1', 'Author 1');

-- Insert data into Books table
INSERT INTO `Books` (`bookID`, `title-book`, `authors-book`, `genre-book`, `stock-book`, `price`, `isbn`, `publisher`, `sinopsis-book`, `transaksiID`, `customerID`)
VALUES 
(1, 'Book Title 1', 'Author 1', 'fantasy', 10, 19.99, '1234567890', 'Publisher A', 'A thrilling adventure.', 1, 1);

-- Insert data into Employe table
INSERT INTO `Employe` (`employeID`, `name-employee`, `contact-employee`, `bookID`, `email-employee`, `role_employee`, `stock-UpdateID`)
VALUES 
(1, 201, '987-654-3210', 1, 'employe1@example.com', 'admin', 1);

-- Insert data into Stock Update table
INSERT INTO `Stock Update` (`stock-UpdateID`, `bookID`, `stockDate`, `quantityStock`, `reasonStock`)
VALUES 
(1, 1, NOW(), 50, 'Initial Stock');

-- Insert data into Sales Transaksi table
INSERT INTO `Sales Transaksi` (`transaksiID`, `transaksiDate`, `totalAmount`, `payment-methode`, `orderID`, `employeID`)
VALUES 
(1, NOW(), 100.00, 'cash', 1, 1),
(2, NOW(), 40.00, 'cash', 2, 1),
(3, NOW(), 30.00, 'e-wallet', 3, 1),
(4, NOW(), 20.00, 'e-wallet', 4, 1),
(5, NOW(), 100.00, 'e-wallet', 5, 1),
(6, NOW(), 80.00, 'transfer bank', 6, 1),
(7, NOW(), 90.00, 'transfer bank', 7, 1),
(8, NOW(), 20.00, 'cash', 8, 1),
(9, NOW(), 100.00, 'cash', 9, 1),
(10, NOW(), 40.00, 'transfer bank', 10, 1),
(11, NOW(), 30.00, 'transfer bank', 11, 1),
(12, NOW(), 20.00, 'virtual bank', 12, 1),
(13, NOW(), 100.00, 'cash', 13, 1),
(14, NOW(), 40.00, 'virtual bank', 14, 1),
(15, '2023-01-15 10:00:00', 30.00, 'cash', 15, 1),
(16, '2023-01-20 12:30:00', 20.00, 'e-wallet', 16, 1),
(17, '2023-01-25 15:45:00', 100.00, 'cash', 17, 1),
(18, '2023-02-10 09:15:00', 40.00, 'virtual bank', 18, 1),
(19, '2023-02-18 16:50:00', 30.00, 'cash', 19, 1),
(20, '2023-03-05 11:20:00', 20.00, 'virtual bank', 20, 1),
(21, '2023-03-22 14:35:00', 100.00, 'cash', 21, 1),
(22, '2023-04-10 10:40:00', 40.00, 'virtual bank', 22, 1),
(23, '2023-04-18 13:00:00', 30.00, 'cash', 23, 1),
(24, '2023-05-02 09:50:00', 20.00, 'virtual bank', 24, 1),
(25, '2023-05-20 15:30:00', 100.00, 'cash', 25, 1);

-- Insert data into Order table
INSERT INTO `Order` (`orderID`, `OrderDate`, `TotalOrderAmount`, `customerID`, `transaksiID`)
VALUES 
(1, NOW(), 100.00, 1, 1),
(2, NOW(), 40.00, 2, 2),
(3, NOW(), 30.00, 3, 3),
(4, NOW(), 20.00, 4, 4),
(5, NOW(), 100.00, 5, 5),
(6, NOW(), 80.00, 6, 6),
(7, NOW(), 90.00, 7, 7),
(8, NOW(), 20.00, 8, 8),
(9, NOW(), 100.00, 9, 9),
(10, NOW(), 40.00, 10, 10),
(11, NOW(), 30.00, 11, 11),
(12, NOW(), 20.00, 12, 12),
(13, NOW(), 100.00, 13, 13),
(14, NOW(), 40.00, 14, 14),
(15, NOW(), 30.00, 15, 15),
(16, NOW(), 20.00, 16, 16),
(17, NOW(), 100.00, 17, 17),
(18, NOW(), 40.00, 18, 18),
(19, NOW(), 30.00, 19, 19),
(20, NOW(), 20.00, 20, 20),
(21, NOW(), 100.00, 21, 21),
(22, NOW(), 40.00, 22, 22),
(23, NOW(), 30.00, 23, 23),
(24, NOW(), 20.00, 24, 24),
(25, NOW(), 100.00, 25, 25);


-- Insert data into Shipment-Address table
INSERT INTO `Shipment-Address` (`shipment-addressID`, `shipment-address-city`, `shipment-address-country`, `shipment-address-state`, `shipment-address-postal-code`, `shipmentID`)
VALUES 
(1, 'City A', 'indonesia', 'State A', '12345', 1);

-- Insert data into Name-Employee table
INSERT INTO `Name-Employee` (`name-employeeID`, `first-name-employee`, `last-name-customer`, `username-employee`, `employeID`)
VALUES 
(1, 'John', 'Doe', 'johndoe', 1);

-- Query 1: Total orders and total amount for each customer, ordered by total amount in descending order
CREATE TABLE IF NOT EXISTS `mydb`.`customer_order` AS
SELECT 
    c.`customerID`,
    CONCAT(nc.`first-name-customer`, ' ', nc.`last-name-customer`) AS `Customer Name`,
    st.`payment-methode` AS `Payment Method`,
    COUNT(o.`orderID`) AS `Total Orders`,
    SUM(o.`TotalOrderAmount`) AS `Total Order Amount`
FROM `Customer` c
INNER JOIN `Name-Customer` nc ON c.`customerID` = nc.`customerID`
INNER JOIN `Order` o ON c.`customerID` = o.`customerID`
INNER JOIN `Sales Transaksi` st ON o.`transaksiID` = st.`transaksiID`
GROUP BY c.`customerID`, nc.`first-name-customer`, nc.`last-name-customer`, st.`payment-methode`
ORDER BY `customerID` ASC;

-- Query 2: Book transactions with stock updates in the last 60 days
CREATE TABLE IF NOT EXISTS `mydb`.`book_transaction` AS
SELECT 
    b.`bookID`,
    b.`title-book`,
    MAX(su.`stockDate`) AS `Last Stock Update`,
    SUM(su.`quantityStock`) AS `Total Stock Added`
FROM `Books` b
INNER JOIN `Stock Update` su ON b.`bookID` = su.`bookID`
WHERE su.`stockDate` >= NOW() - INTERVAL 60 DAY
GROUP BY b.`bookID`
ORDER BY `Last Stock Update` DESC;

-- Query 3: Total transactions and total amount managed by employees in a specific role
CREATE TABLE IF NOT EXISTS `mydb`.`employee_transaction` AS
SELECT 
    e.`employeID`,
    CONCAT(ne.`first-name-employee`, ' ', ne.`last-name-customer`) AS `Employee Name`,
    COUNT(st.`transaksiID`) AS `Total Transactions`,
    SUM(st.`totalAmount`) AS `Total Amount`
FROM `Employe` e
INNER JOIN `Name-Employee` ne ON e.`employeID` = ne.`employeID`
INNER JOIN `Sales Transaksi` st ON e.`employeID` = st.`employeID`
WHERE e.`role_employee` = 'admin'
GROUP BY e.`employeID`, ne.`first-name-employee`, ne.`last-name-customer`
ORDER BY `Total Amount` DESC;

-- Query 4: Total shipments for each city with a 'pending' status
CREATE TABLE IF NOT EXISTS `mydb`.`shipment_transaction` AS
SELECT 
    sa.`shipment-address-city` AS `City`,
    COUNT(s.`shipmentID`) AS `Total Shipments`
FROM `Shipment` s
INNER JOIN `Shipment-Address` sa ON s.`shipmentID` = sa.`shipmentID`
WHERE s.`status-shipment` = 'pending'
GROUP BY sa.`shipment-address-city`
ORDER BY `Total Shipments` DESC;

-- Query 5: Recommended books for a specific genre with stock > 0
CREATE TABLE IF NOT EXISTS `mydb`.`rekomendasi_customer` AS
SELECT 
    r.`genre-book`,
    r.`title-book` AS `Recommended Book`,
    r.`authors-book`
FROM `Rekomendasi` r
INNER JOIN `Books` b ON r.`bookID` = b.`bookID`
WHERE r.`genre-book` = 'fantasy' AND b.`stock-book` > 0
GROUP BY r.`title-book`, r.`authors-book`
ORDER BY r.`title-book` ASC;

-- tambahan 
CREATE TABLE IF NOT EXISTS `mydb`.`sales_trend_last_week` (
    `Tanggal` DATE NOT NULL,
    `Total Transaksi` INT NOT NULL,
    `Total Penjualan` DECIMAL(10,2) NOT NULL,
    `Rata-rata Penjualan` DECIMAL(10,2) NOT NULL,
    `Pertumbuhan (%)` DECIMAL(10,2) NULL,
    PRIMARY KEY (`Tanggal`)
);

INSERT INTO `mydb`.`sales_trend_last_week` (`Tanggal`, `Total Transaksi`, `Total Penjualan`, `Rata-rata Penjualan`, `Pertumbuhan (%)`)
SELECT 
    DATE(st.transaksiDate) AS `Tanggal`,
    COUNT(st.transaksiID) AS `Total Transaksi`,
    SUM(st.totalAmount) AS `Total Penjualan`,
    ROUND(AVG(st.totalAmount), 2) AS `Rata-rata Penjualan`,
    ROUND(
        (SUM(st.totalAmount) - 
        LAG(SUM(st.totalAmount)) OVER (ORDER BY DATE(st.transaksiDate))) / 
        LAG(SUM(st.totalAmount)) OVER (ORDER BY DATE(st.transaksiDate)) * 100, 
        2
    ) AS `Pertumbuhan (%)`
FROM 
    `Sales Transaksi` st
WHERE 
    st.transaksiDate >= '2023-01-01 00:00:00' -- Data mulai dari tahun 2023
    OR st.transaksiDate >= NOW() - INTERVAL 7 DAY -- Data minggu terakhir
GROUP BY 
    DATE(st.transaksiDate)
ORDER BY 
    DATE(st.transaksiDate) ASC;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
